apiVersion: apps/v1
kind: Deployment
metadata:
  name: mi-deployment
  namespace: guscontre-dev
  labels:
    app: mi-app
    areanegocio: tecnologia
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mi-app
  template:
    metadata:
      labels:
        app: mi-app
    spec:
      annotations:
          image.openshift.io/triggers:  |
            [
              {
                "from": {
                  "kind": "ImageStreamTag",
                  "name": "ejercicio-codigo-s2i:latest"
                },
                "fieldPath": "spec.template.spec.containers[?(@.name==\"contenedor-principal\")].image"
              }
            ]
      containers:
        - name: contenedor-principal
          image: image-registry.openshift-image-registry.svc:5000/guscontre-dev/ejercicio-codigo-s2i:latest
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: "500m"
              memory: "800Mi"
            limits:
              cpu: "1000m"
              memory: "1500Mi"
          envFrom:
            - configMapRef:
                name: mi-configmap   # <-- OJO: indentado debajo de configMapRef
            - secretRef:
                name: mi-secret
---
apiVersion: v1
kind: Service
metadata:
  name: mi-servicio
  namespace: guscontre-dev
spec:
  selector:
    app: mi-app
  ports:
    - protocol: TCP
      port: 4000        # Puerto del Service
      targetPort: 3000  # Puerto del contenedor
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mi-configmap
  namespace: guscontre-dev
data:
  DATABASE: "192.168.1.1" 

---
apiVersion: v1
kind: Secret
metadata:
  name: mi-secret
  namespace: guscontre-dev
type: Opaque
data:
  PASSWORD: 'aG9sYQo='

--- 
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: mi-hpa
  namespace: guscontre-dev
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: deployment
    name: mi-deployment
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 100